Repository jhunterh/Mancala-GPU-Project, pull requests merged in 2023-02, with the labels that each got.

#3 Create framework for multiple games
  .gitignore
  Makefile
  README.md
  framework/include/GameBoard.h
  framework/include/Player.h
  framework/include/PlayerManager.h
  framework/include/RandomPlayer.h
  framework/src/PlayerManager.cpp
  framework/src/RandomPlayer.cpp
  games/mancala/include/game.h
  games/mancala/src/GameBoard.cpp
  games/template/include/game.h
  games/template/src/GameBoard.cpp
  include/GameManager.h
  include/MancalaStatic.h
  include/MonteCarloPlayer.h
  include/Player.h
  include/RandomPlayer.h
  include/SimulationPolicy.h
  include/SimulationPolicyCPU.h
  simulation/src/main.cpp
  src/GameManager.cpp
  src/MonteCarloPlayer.cpp
  src/RandomPlayer.cpp
  src/SimulationPolicyCPU.cpp
  src/main.cpp
Labels: documentation, enhancement

#5 Updated getBoardResult to fix end result bug
  framework/include/GameBoard.h
  framework/src/RandomPlayer.cpp
  games/mancala/src/GameBoard.cpp
  simulation/src/main.cpp
Labels: bug

#6 1 mancala monte carlo single threaded implementation
  .gitignore
  Makefile
  README.md
  framework/include/GameBoard.h
  framework/include/GameTypes.h
  framework/include/MonteCarloPlayer.h
  framework/include/MonteCarloTypes.h
  framework/include/PlayerManager.h
  framework/src/MonteCarloPlayer.cpp
  framework/src/PlayerManager.cpp
  games/mancala/include/game.h
  games/template/include/game.h
Labels: enhancement
